# Site settings
title: Thoughts in Binary
email: timvazquez@gmail.com
url: https://inusara.github.io
description: >
  "As I learn, I write." A diary of musings of an introvert coder.
repo:
  title: github
  url: https://github.com/inusara/inusara.github.io
  caption: "View on Github"

# Color settings (hex-codes without the leading hash-tag)
color:
  primary-dark: '#000000'
  links: '#219ab3'

# Footer settings
footer: inusara.github.io

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: envelope
    url: mailto:timvazquez@gmail.com
    caption: "Email"
  - title: github
    url: https://github.com/inusara
    caption: "GitHub"
  - title: codepen
    url: http://codepen.io/inusara
    caption: 'CodePen'

# Build settings
markdown: kramdown
permalink: pretty
